10 Cпринт. 1 Попытка.
cuttiecat/java-filmorate pull request #5
Opened 2023-06-24 03:49 UTC by cuttiecat

Пытаюсь пройти тесты для ревью.

2023-06-24 07:45 UTC, EugeneLenkevich requested changes
Привет, Светлана, спасибо за PR

В целом все отлично :)
Хотелось бы только остановить внимание на такой вещи как разделение бязанностей по слоям.  Оставил несколько коментариев
Обычно обязанности распределаются вот так

По классике обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Пустая строка тут лишняя, это же единый блок объявления :)

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

Он для финальных поле конструктор сгенерирует :)
private final FilmService filmService;

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Getting film by id: " + id);
Тут мы логируем бизнес-операции, логичнее это делать на уровне сервиса, на уровне контроллеров у нас обработка http-запросов, то есть так немножко обязанности слоев перемешиваются :)

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> allFilms = filmStorage.findAll();
Выборка и сортировка данных - это обязаность хранилища, лучше в нем сделать сооветствующий метод, а тут его вызывать. Иначе мы вытаскиваем детали реализации хранилища (а они кстати могу сильно меняться в дальнейшем) на уровень бизнес-логики(сервисов) :)

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (User user1friend : user1friends) {
Опять таки, выборку данных лучше преенести на слой ниже :)

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +    public static void validate(User user) {
static тут не нужен, это же спринговый бин :)

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    Map<Long, Film> films = new LinkedHashMap<>();
private

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    Map<Long, User> users = new LinkedHashMap<>();
private

2023-06-24 07:45 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTests.java
> +//package ru.yandex.practicum.filmorate;
Закоментированный код лучш не оставлять. Его потом трудно будет обратно приделать потому что, скорее всего, все вокруг поменяется, а для истории есть git :)

2023-06-24 17:36 UTC, EugeneLenkevich requested changes
Не совсем понимаю что тут поменялось. Вот смотри, сервис валидации

![image](https://github.com/cuttiecat/java-filmorate/assets/109306643/999f470b-ca07-4692-8419-97a26f8c37ed)

Тут надо или static убрать или аннотацию @Service, но лучше убрать static и инжектить валидатор, как, в общем то судя по комитам, до этого и было

2023-06-24 19:55 UTC, cuttiecat commented
> 

Если убрать static, то потом тесты не проходят. А решения я по ним не могу найти.
![image](https://github.com/cuttiecat/java-filmorate/assets/119683620/289446ec-eb7b-4c3c-a687-bffb9d79dc47)

2023-06-25 03:35 UTC, EugeneLenkevich approved these changes
Ок, пусть будет так, спасибо :)

2023-06-25 03:55 UTC, merged